name: Keeper Wallet Jira Action
description: Send reports to jira to move tasks based on commit messages
inputs:
  component:
    description: Component
  github-token:
    description: GITHUB_TOKEN
    required: true
  hooks-url:
    description: HOOKS_URL
    required: true
  hook-merge:
    description: HOOK_MERGE
  hook-release:
    description: HOOK_RELEASE
runs:
  using: node16
  main: build/index.js
