name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - run: yarn --frozen-lockfile
      - run: yarn semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set major version tag pointer
        if: steps.semantic-release.outputs.new-release-published == 'true'
        run: |
          MAJOR=$(echo $RELEASE_VERSION | cut -d . -f 1)
          git tag -f $MAJOR
          git push origin $MAJOR --force
        env:
          RELEASE_VERSION: v${{ steps.semantic-release.outputs.new-release-version }}
    outputs:
      new-release-published: ${{ steps.semantic-release.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic-release.outputs.new-release-version }}

  report-merge:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: ./
        with:
          hooks-url: ${{ secrets.HOOKS_URL }}
          hook-merge: ${{ secrets.HOOK_MERGE }}
          release-version: ${{ needs.release.outputs.new-release-version }}

  report-release:
    needs: [release, report-merge]
    if: needs.release.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: ./
        with:
          component: Other
          hooks-url: ${{ secrets.HOOKS_URL }}
          hook-release: ${{ secrets.HOOK_RELEASE }}
          release-version: v${{ needs.release.outputs.new-release-version }}
