name: Release
on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: ./
        with:
          component: Other
          github-token: ${{ secrets.GITHUB_TOKEN }}
          hooks-url: ${{ secrets.HOOKS_URL }}
          hook-release: ${{ secrets.HOOK_RELEASE }}
